enum TransactionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  STAKE = 'STAKE',
  UNSTAKE_PRINCIPAL = 'UNSTAKE_PRINCIPAL',
  STAKING_REWARD = 'STAKING_REWARD',
  SWAP_FIAT_TO_CRYPTO = 'SWAP_FIAT_TO_CRYPTO',
  SWAP_CRYPTO_TO_FIAT = 'SWAP_CRYPTO_TO_FIAT',
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT',
}